
//@version=5
strategy("ZOMATO Strategy", 
    overlay=true, 
    initial_capital=100000.0, 
    commission_type=strategy.commission.percent,
    commission_value=0.002)

// Trading Hours
var start_time = timestamp("09:15")
var end_time = timestamp("15:20")
is_trading_time = time >= start_time and time <= end_time

// Indicators
ema_50 = ta.ema(close, 50)
[macd_line, signal_line, hist] = ta.macd(close, 12, 26, 9)
sma_20 = ta.sma(close, 20)

// Entry Conditionsif sma > 100 and is_trading_time
    strategy.entry("Long", strategy.long)
if ema < 50 and is_trading_time
    strategy.entry("Long", strategy.long)

// Exit Conditionsif willr > 0 and is_trading_time
    strategy.close("Long")
if ta.crossover(macd, -10) and is_trading_time
    strategy.close("Long")


// Risk Management
var stop_loss = 0.02
var take_profit = 0.03
var max_pos_size = 0.1
