# config.yaml

# API Selection
api_provider: "ollama"  # Options: "openai", "ollama", "groq"

# Ollama Configuration
ollama:  # Changed from 'Ollama' to 'ollama' for consistency
  model: "llama3.2:1b"  # Options: "algo_DD", "llama3.2", "qwen2.5:1.5b","0xroyce/plutus", "llama3.2:1b"

# OpenAI Configuration
openai:  # Changed from 'OPENAI' to 'openai' for consistency
  api_key: "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"
  model: "gpt-4-turbo-preview"

# Groq Configuration
groq:
  api_key: "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"
  model: "llama-3.1-70b-versatile"

# # Algorithm Configuration
# algo_agent:
#   number_of_algorithms: 1

# Backtesting_agnet.py Configuration
backtesting:
  stocks_per_trade: 10
  historical_data_path: "agents/backtesting_agent/historical_data/"
  # algorithm_path: "output/logs/"
  # output_path: "output/"
  lookback_days: 30

# Checker_agnet.py Configuration
configuration:
  Return [%]: 30.00
  max_drawdown: 20
  number of checking: 10
  reduce %: 5

# Data_download.py Configuration

historical_days: 120
chunk_size: 7
data_interval: "1m"
max_attempts: 12
delay_between_attempts: 90
delay_between_chunks: 65
batch_delay: 180  # New parameter for delay between 30-day batches


